name: CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

env:
  CARGO_TERM_COLOR: always
  MUTAGEN_COMMIT: f8249256c40769c916b5b00bd284f204d5540588
  COV_THRESHOLD: 100.0
  MUTAGEN_THRESHOLD: 100.0
  CRATE_PATHS: . # package names separated by ";" in publish order if the repository is a Cargo workspace, else "."

jobs:

  test:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.51.0
          profile: minimal
          override: true
      - name: Build
        run: cargo build --all-targets
      - name: Test
        run: cargo test

  check-coverage-mutations:
    runs-on: ubuntu-18.04
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-03-25
          profile: minimal
          components: llvm-tools-preview
          override: true
      - name: Install grcov
        run: cargo install grcov
      - name: Install mutagen
        run: bash .github/workflows/scripts/install_mutagen.sh
      - name: Run coverage
        run: bash .github/workflows/scripts/check_coverage.sh
      - uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage
          if-no-files-found: error
          retention-days: 1
      - name: Run mutation tests
        run: bash .github/workflows/scripts/check_mutations.sh

  lint:
    runs-on: ubuntu-18.04
    needs: check-coverage-mutations
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.51.0
          profile: minimal
          components: rustfmt, clippy
          override: true
      - name: Install other dependencies
        run: sudo apt-get install moreutils dos2unix
      - name: Check encoding
        run: isutf8 **/*
      - name: Check line endings
        run: bash .github/workflows/scripts/check_line_endings.sh
      - name: Check TODOs
        run: bash .github/workflows/scripts/check_todos.sh
      - name: Run clippy
        run: cargo clippy --all-targets -- -D warnings $(cat .lints | cut -f1 -d"#" | tr '\n' ' ')
      - name: Run rustfmt
        run: cargo fmt -- --check
      - name: Run cargo-deny
        uses: EmbarkStudios/cargo-deny-action@v1
        with:
          command: check
